services:
    web:
        image: ${APP_NAME}:latest
        build:
            target: web
            context: .
        env_file:
            - .env
        ports:
            - "8000:80"
        depends_on:
            - db
        networks:
            - app-network
        volumes:
            - .:/var/www/html

    db:
        platform: "linux/amd64"
        image: mysql:8.0
        env_file:
            - .env
        environment:
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
#            MYSQL_USER: ${DB_USERNAME}
#            MYSQL_PASSWORD: ${DB_PASSWORD}
        ports:
            - "3306:3306"
        networks:
            - app-network
        volumes:
            - dbdata:/var/lib/mysql

networks:
    app-network:
        driver: bridge

volumes:
    dbdata:
